version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./tictactoe-backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    image: ninjashadow/tictactoe:backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    volumes:
      - ./TicTacToe backend:/app
    stdin_open: true
    tty: true
    command: bash -c "python manage.py runserver 0.0.0.0:${BACKEND_PORT}"

  frontend:
    container_name: frontend
    build:
      context: ./tictactoe-frontend
      args:
        BACKEND_IP: ${API_IP}
    image: ninjashadow/tictactoe:frontend_v1.4
    ports:
      - "80:80"
    env_file:
      - .env
    # volumes:
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge

  