version: '3.8'

services:
  frontend:
    container_name: react-app
    build:
      context: ./tictactoe-frontend
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./tictactoe-frontend:/app
    stdin_open: true
    tty: true

  backend:
    container_name: django-app
    build:
      context: ./TicTacToe backend
      # dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./TicTacToe backend:/app
    stdin_open: true
    tty: true
    command: bash -c "python manage.py runserver 0.0.0.0:8000"